baseURL = "https://kishinshuichiro.github.io/"
languageCode = "zh-cn"
title = "Meditationes Sansepulcristarum"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = false
  ShowFirstPost = false
  mainSections = ["posts"]

[params.homeInfoParams]
  Title = "Welcome"
  Content = "测试一下。\n\n*Liebe dein Symptom wie dich selbst.*"


[params.cover]
  hiddenInList = false
  hiddenInSingle = false

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
